### ISSUE TITLE
Filter out results on arrays before displaying on Plugin element

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/conforma-server#1004]
Required specifically for removing the `admin` preferences to be selected in templates e.g. GrantUserPermission.

### Existing implementation

Currently the list of permissions is displayed by `Checkbox` plugin element, which only uses an array passed on (or received by a API query result) to be displayed, there is no filters applied.
![Screen Shot 2023-01-17 at 1 48 06 PM](https://user-images.githubusercontent.com/16461988/212791768-3c474e66-d7f2-4527-96ef-7f2cde0c27d3.png)

The current API query used will return ALL permissions based on the orgId and/or userId received:
![Screen Shot 2023-01-17 at 1 48 30 PM](https://user-images.githubusercontent.com/16461988/212791762-4a896210-953d-4cab-904d-4cfc1efddd76.png)

It would be tricky to add some filtering to the `Checkbox` plugin or to change the existing `user-permissions` end-point

### Proposed Solution
Create a new evaluator custom function to filter an array, which would be what the `checkboxes` parameter would call, and pass as one of the parameters the result from the API query to `user-permissions`. 

Syntax:

```
filter( valuesArray, options }

Where "options" is:
{
  key?: string
  values: string | string[] (in principle could be numbers or any primitive type)
  rule?: "exclude" | "include (default: "exclude")
}
```

Parameters types explained:
`valuesArray`: array of objects OR strings
`key`: which key to filter (optional -- omitted means the input is an array of strings/primitives not array of objects
`values`: array of values to filter OR single value
`rule`: enum to say if should include or exclude these keys on the result (default "exclude" would you say?)

**Comment by CarlosNZ** [comment]
Couple of suggested amendments:

> Create a new function to filter an array...,
"Create a new evaluator custom function to filter an array..."

Parameters:
- array of objects OR STRINGS
- ~~strings~~ ??
- key to filter (optional -- omitted means the input is an array of strings/primitives not array of objects
- array of values to filter OR single value 
- enum to say if should include or exclude these keys on the result (default "exclude" would you say?)

**Comment by CarlosNZ** [comment]
Syntax:

```
filter( valuesArray, options }

Where "options" is:
{
  key?: string
  values: string | string[] (in principle could be numbers or any primitive type)
  rule?: "exclude" | "include (default: "exclude")
}
```

Sound okay?

**Comment by nmadruga** [comment]
> Syntax:
> 
> ```
> filter( valuesArray, options }
> 
> Where "options" is:
> {
>   key?: string
>   values: string | string[] (in principle could be numbers or any primitive type)
>   rule?: "exclude" | "include (default: "exclude")
> }
> ```
> 
> Sound okay?

Yep. Thanks for adding that info. I wrote the issue too quick!
