### ISSUE TITLE
Test mode -- to avoid sending out notifications to real users

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/conforma-server#1028]
Now that we have real users on a real system, we should be careful about testing with live data. It's very easy to cause actions that can send out notifications to real users, which would be quite uncool.

So we probably need some kind of "test mode" that we can enable whenever a snapshot is installed on a non-live server, which would then re-direct all emails to whoever is testing. Or something like that. 

@Fergie-nz has suggested Mailhog, which might be a good idea, but not sure how that would work on a demo server though.

Something to discuss further.

**Comment by jagoje** [comment]
@CarlosNZ any updates on this one?

**Comment by CarlosNZ** [comment]
It shouldn't be that hard to implement, we just need to think about it a bit carefully, as we do want some emails going out during local testing (so we can click on the links, etc.).

**Comment by CarlosNZ** [comment]
This should be a setting in "preferences.json", but we need a way to update it on the server, which means making a small Admin UI for preferences.

I think for now it'll just be a JSON text editing box.

**Comment by CarlosNZ** [comment]
@jagoje I've done a basic implementation of this. I'll make a build of it and put it on the demo server later today, then I'll show you how it works.

You basically have to provide a "testingEmail" (which you can now do in the UI), then whenever the system is not the official "live" system, *all* emails get sent to the testingEmail instead of the configured recipients.
