### ISSUE TITLE
Submenus for Application List, Database, etc.

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/conforma-server#1044]
Needs a bit of thought on how to extend the current schema to configure these.

It's pretty simple for "Data Views", but the others are not straightforward because of the interaction with Categories.

**Comment by CarlosNZ** [comment]
Replaces issue https://github.com/openmsupply/conforma-templates/issues/181

**Comment by CarlosNZ** [comment]
There's not really a simple way to structure the schema to incorporate sub-menus without restructuring it completely and specifying exactly where each individual template should appear (currently it's just per category).

So here's a way of doing it that I think will work and doesn't involve a major re-structure. All we need to do is treat the "template_categories" *as* sub-menus. If they're in the Dashboard, they already appear in groups, so we just need to do the same thing for the menus they appear in.

It's probably a good idea then, to break templates down into smaller categories. However, we can give multiple categories the same name if need be, which would mean they'd still appear in the same "group" in the Dashboard (just with a different, unique category code). (But maybe this isn't necessary, we'll see)

**Comment by jagoje** [comment]
@CarlosNZ - Suggested layout: https://docs.google.com/document/d/18WabPSEb1y2IcP17IqGF3jMe30WyraUdjsxPSt3fUXA/edit#
