### ISSUE TITLE
Rules for Dashboard appearance (per template)

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/conforma-server#1045]
As in, some templates should always appear on the Dashboard, some should only appear if there's some activity in progress (Corrections workflows for example).

I'll need to break down all the possible rules and what that means (for both reviewers and applicants), but that's the basic idea.

**Comment by jagoje** [comment]
It would be super in the future to also have visibility based on permissions as well.

**Comment by CarlosNZ** [comment]
My suggestion for this:

- Add a new column to "template" table called `dashboard_restrictions`, which is an array of strings (or `null`)
- Each string in the array is the name of a filter ("draftReviews", "
- When rendering the dashboard, if any of the relevant filters (for the current user) have counts of more than 0, then we display it on the dashboard, otherwise hide it.
- "Empty" (`null`) values means always display (if "DASHBOARD" specified in category of course)

There are a couple of scenarios I can think of where this won't _quite_ work, so we should talk it through.

**Comment by CarlosNZ** [comment]
> There are a couple of scenarios I can think of where this won't _quite_ work, so we should talk it through.

There's only one, really. That is, if a staff member has made a corrections request to a company, then it would be nice if the "Start new correction application" option showed up at that point. However, this is not that easy to do, since it can only be conditional based on *this* application type, not the staff member's "request" application. As far as the applicant goes, there is no application yet.

One thing we can do is put the URL to start the actual application in the Correction Request email. However, this doesn't account for when an applicant wants to initiate their own correction request, so we'd still need to put this somewhere other than the Dashboard (the "Manage" menu is really the only other place that makes sense).
