### ISSUE TITLE
Remove need to pass GraphQL endpoint on calls of Evaluator

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/conforma-server#324]
Yeah, but if you're passing an external URL in the query expression, you should be able to omit the `endpoint` field in the `graphQLConnection` object that you pass in, and the evaluator should still work, hence we should make sure there is a test that handles that case.

(Use case: if using the evaluator for something else (i.e. not IRIMS), you might not even have a local GraphQL connection, so why require an endpoint field for external queries?)

_Originally posted by @CarlosNZ in https://github.com/openmsupply/application-manager-server/pull/321#discussion_r621659175_

**Comment by CarlosNZ** [comment]
Also covered by #1001
