### ISSUE TITLE
Snapshot + Template builder: Update "Join a company" in the Laos Workflow to be using Search field instead of dropdown to select a company

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/conforma-server#389]

**Comment by nmadruga** [comment]
> > update to use Search field instead of dropdown to select a company
> 
> What do you think -- search by name, minimum 3 chars?

I kind of like - if not much work needed - to use more than one field to search. Since we have this ability on a GraphQL query. I would say: name or registration. What do you think?

**Comment by CarlosNZ** [comment]
> I rather have - if not much work needed - to use more than one field to search. Since we have this ability on a GraphQL query. I would say: name or registration. What do you think?

Depends how "secret" the org names should be.  The purpose of searching by rego only was so you couldn't easily browse a list of all the companies in the system, but I'm not sure how important that is here. Basically, it depends what Valerio says.

**Comment by CarlosNZ** [comment]
I think it looks weird having it all stuck over to the left like that. The "container" should probably be centered so it looks like:
![Screen Shot 2021-07-12 at 12 18 53 PM](https://user-images.githubusercontent.com/5456533/125214542-d0134000-e30b-11eb-9aee-ae6ac8499296.png)

Are you imagining that three boxes would be on one row? If two is the limit, then probably just set the max-width on the containing div to just fit two elements, and then center that container.

Do you think?
