### ISSUE TITLE
Bug: Problem when assigning same permission to user (on self-assignment) would block the user from reviewing

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/conforma-server#578]
Noted prior to Angola demo 2: Snapshot on https://irims-demo.msupply.org:50008/

**Comment by CarlosNZ** [comment]
> would clock the user from reviewing

_clock_?

Also -- can you clarify the issue a bit more specifically?

**Comment by nmadruga** [comment]
> > would clock the user from reviewing
> 
> _clock_?
> 
> Also -- can you clarify the issue a bit more specifically?

Oops. block : D

**Comment by nmadruga** [comment]
Noticed during my rush to get things in place for Angola. Somehow I had the same user having double assignments generated to the same application/stage (after the reviewAssignment was generted). And I guess it might be due to having selected the same type of assignment to that use twice, but I'm not sure. That's why the issue is created to check that.

The problem happening in the snapshot (using latest Drug Registration template version): 
[demo_angola_pt_10.zip](https://github.com/openmsupply/application-manager-server/files/7173869/demo_angola_pt_10.zip) better to test this locally so you have direct access to the DB.

If you try submitting the review of "Avaliador Básico" to get it to the next stage, then log in as "Avaliador Supervisor" I think that's how you can see the bug happening... You try to self-assign to you and you can see there are 2 options for each section, then after assigning it clock both - probably due to the logic of finding if there is already on reviewAssignment then block others... But not sure. It's a strange bug, that probably happens in specific misconfigured system.

The trouble is that, when this happens it creates a nasty bug, that doesn't allow you to review anymore.

**Comment by CarlosNZ** [comment]
> But not sure. It's a strange bug, that probably happens in specific misconfigured system.

Yes, true. Which is why I'm more and more leaning away from relying on configuration to make core functionality work -- it's too easy to break it. It's not an easy problem to sort, but we can discuss.

**Comment by CarlosNZ** [comment]
> Yes, true. Which is why I'm more and more leaning away from relying on configuration to make core functionality work -- it's too easy to break it. It's not an easy problem to sort, but we can discuss.

Core action functionality is now pretty solid and safely removed from breaking in the template builder
