### ISSUE TITLE
Database lists  - All system data tables

### ISSUE THREAD

**Issue by jagoje** [openmsupply/conforma-server#697]
IMPORTANT: Clarification needed. PSM Wrote: Needs clarification, was not present in previous matrix.

### Reference
Final Requirements Matrix 1 - General - Row 1

* 1 day for configuration + testing

### Configration
We already have some of this lists. And those are meant for internal users only! What an external user can see currently is only Users/Companies that they relate to - which should be persisted.

Data tables required for:
- Internal users
- External users
- Approved companies
- Approved products
- Products that have been canceled

Extra issue to fix things on external user lists: https://github.com/openmsupply/conforma-server/issues/721

**Comment by CarlosNZ** [comment]
What is this, specifically?

**Comment by nmadruga** [comment]
I'll update with something more specific and connected to a thing from the list of Final Requirements Matrix....

**Comment by jagoje** [comment]
List of database tables: https://docs.google.com/document/d/16edxZ6Av4T43q-ZIfxE-5HuqBIHP5L8sDcRyxsbc75k/edit#
