### ISSUE TITLE
Update Permission names & Descriptions

### ISSUE THREAD

**Issue by jagoje** [openmsupply/conforma-server#717]

**Comment by nmadruga** [comment]
Should be displaying on template to grant internal user permissions

**Comment by nmadruga** [comment]
Noticed today that Grant Permissions on our current snapshot isn't correct - Carl is updating it. We have already added the specific names and descriptions to each user role as described in: https://docs.google.com/document/d/1c9izflT2k3ebUOysTLh4gsItpA5IQYTJ22x71oxR1Gk
