### ISSUE TITLE
Medicine registration - Template fields

### ISSUE THREAD

**Issue by jagoje** [openmsupply/conforma-server#722]
The list of fields described in here were prior to our visit, so this issue will be closed and one listing what needs to be changed on the existing P1-ProdRegistrationLong template is detailed in: https://github.com/openmsupply/conforma-templates/issues/16

**Comment by jagoje** [comment]
A lot of this template can be taken from this issue: https://github.com/openmsupply/application-manager-templates/issues/7

### Section 1: Application Information (Portuguese)

**Page 1:**
<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-188d80c4-7fff-d07f-aa82-839a5c2fceb2"><div dir="ltr" style="margin-left:-59.25pt;" align="left">

No# (just for ordering) | Field name (English) | Field name (Portuguese) | Description of field | Specific Field validation? | Mandatory
-- | -- | -- | -- | -- | --
1 | Application Type | Tipo de pedido | Drop down list:List items: ​​Nova substância activaSubstância activa conhecidaGenérico | No |  

</div></b>


**Page 2:**
Text heading: Detalhes do requerente
<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-131b2afc-7fff-fce2-f135-a6e68fc93287"><div dir="ltr" style="margin-left:-59.25pt;" align="left">

No# (just for ordering) | Field name (English) | Field name (Portuguese) | Description of field | Specific Field validation?
-- | -- | -- | -- | --
1 | Applicant Name |   | pre-filled from the users details | Not editable
2 | Applicant Contact Number |   | pre-filled from the users details | Not editable
3 | Applicant Contact Email |   | pre-filled from the users details | Not editable
4 | Applicant Company Name |   | pre-filled from the users details | Not editable
5 | Applicant Company Address |   | pre-filled from the users details | Not editable

</div></b>

**Comment by jagoje** [comment]
Page 3: CARACTERIZAÇÃO DO MEDICAMENTO

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-d69068b1-7fff-e33d-a5a3-f4846f1890d9"><div dir="ltr" style="margin-left:-59.25pt;" align="left">

No# (just for ordering) | Field name (English) | Field name (Portuguese) | Description of field | Specific Field validation?
-- | -- | -- | -- | --
1 | Drug Name(commercial or invented) | Nome do medicamento (comercial ou de fantasia) | Free text | No (eventually we will want it to chick for similar names)
2 | Generic name of active substance(s) | Nome da (s) substância activa (s) | Searchable list (ingredients appear after 2 characters)List is here for now: (updating atc codes still)https://drive.google.com/file/d/1AWIh2XVqgstxF3-LCayDFGzSlUpvy8Yj/view?usp=sharing | Yes - prefills the below fields.We will need to think of what happens if an applicant needs to enter a new ingredient. (suggest separate workflow)
3. | Pharmacotherapeutic class/code (ATC classification compliance) | Classe Farmacoterapêutica/código (conformidade com a classificação ATC) | Based on the selection above, the associated ATC code is pre-filled | Non-editable
4. | Pharmacotherapeutic Class | Classe Farmacoterapêutica | Based on the selection above, the associated therapeutic class  is pre-filled | Non-editable

</div></b>

**Comment by jagoje** [comment]
Page 4: COMPOSIÇÃO QUALITATIVA E QUANTITATIVA

**Comment by jagoje** [comment]
**Page 5: Fabricantes/Entidade (s) responsável**

Sorry will need to translate this section.

(a table like previously done would be good, but whatever is easiest!!)
1. Product owner: 

- Y/N if Y prefill with applicant details
- Company name
- Address
- Telephone number

3. Finished Product Manufacturer (to do)

- Manufacturer Name
- Manufacture Address
- Processing steps (can select more than 1 - option list attached, needs translating)

4. Active Ingredient Manufacturer

- Manufacture Name
- Manufacture Address
- Processing steps

5. Additional Manufacturers (can be more than one of these..):

- Manufacture Name
- Manufacture Address
- Processing steps

6. Importer Company (if applicable) NOTE! This is a non-mandatory field.

- Same as applicant? Y/N if Y prefill with applicant details
- Company name
- Address
- Telephone number

[Processing Steps .xlsx](https://github.com/openmsupply/application-manager-templates/files/7535672/Processing.Steps.xlsx)

**Comment by jagoje** [comment]
**Section 2: Module 1 documentos**

Page 1

Can some text please be added somewhere "All stated documents are to be provided. If not relevant to the subject product a justification of non-applicability must be provided."

Note: This section is just to upload the following documents
**Documentos complementares**
- Application cover letter
- Receipt of payment of application fee
- Certificate of Pharmaceutical Product(CPP)/ Certificate of Free Sale(CFS)
- Copy of certificate of Drug Registration
- Statement of regulatory status in other countries
- Letter of access from APIMF, CEP or CPQ holder
- Letter of authorisation for the MAH
- Proof of compliance with current Good Manufacturing Practices
-  TSE/BSE animal origin statement
- Summary of product characteristics
- Proposed labelling including primary container and dosage form
- Copy of proposed package insert

Text: Module 1 Sub-modules
"Can some text please be added somewhere "Please upload all relevant documents within the field for each sub-module."
1.4 - INFORMAÇÕES SOBRE OS PERITOS

1.5 - REQUISITOS ESPECÍFICOS

1.6 - AVALIAÇÃO DO RISCO AMBIENTAL

1.7 - INFORMAÇÃO RELATIVA À FARMACOVIGIL NCIA

1.8 - INFORMAÇÃO RELATIVA AOS ENSAIOS CLÍNICOS

**Comment by jagoje** [comment]
**Section 3: Module 2 documentos**

Page 1 
(THE FOLLOWING IS THE TEXT HEADINGS AND ASSOCIATED ATTACHMENT FIELDS)
<img width="521" alt="image" src="https://user-images.githubusercontent.com/88009219/164214021-e2da7255-294b-4b49-a274-fd06331917fd.png">

**Comment by nmadruga** [comment]
Portuguese version for section titles:

## Section 1
### English: Application Information
#### Portuguese: Informações do produto

## Section 2
### English: ?
#### Portuguese: Module 1 documentos

## Section 3
### English: ?
#### Portuguese: Module 2 documentos

**Comment by nmadruga** [comment]
> **Page 5: Fabricantes/Entidade (s) responsável**
> 
> Sorry will need to translate this section.

No problem. This page is pretty similar to what we had, so that's good. Wasn't much work. And now I have the portuguese version as well:

> 1. Product owner

Gerente do produto

> 3. Finished Product Manufacturer 

Fabricante do produto final

> 4. Active Ingredient Manufacturer

Fabricantes dos ingredientes ativos

> 5. Additional Manufacturers

Outros fabricantes envolvidos

> 6. Importer Company

Lista de importadores

> English list details 1
> * Manufacture Name
> * Manufacture Address
> * Processing steps

Portuguese list details 2
- Nome
- Endereço
- Etapas do processamento

> English list details 2
> - Same as applicant? Y/N if Y prefilled with applicant details
> - Company name
> - Address
> - Telephone number

Portuguese list details 2
- Usar detalhes do solicitante?
- Nome da empresa
- Endereço
- Telefone

**Comment by nmadruga** [comment]
Resumos - Módulo 2
### SUB-MÓDULO 2.1 - ÍNDICE
- Índice da documentação científica apresentada no Módulo 2
### SUB-MÓDULO 2.2 - INTRODUÇÃO
- 1.Gupo farmacológico
- 2.Modo de acção e uso clínico proposto
### SUB-MÓDULO 2.3 - RESUMO GERAL DA QUALIDADE
- Relatório relativo aos dados químicos, farmacêuticos e biológicos
Substância activa
- Produto acabado
### SUB-MÓDULO 2.4 - SÍNTESE NÃO CLINICA
- Relatório relativo aos dados não clínicos
### SUB-MÓDULO 2.5 - SÍNTESE CLÍNICA
- Relatório relativo aos dados clínicos
### SUB-MÓDULO 2.6 - RESUMO NÃO CLÍNICO
- 1.Introdução
- 2.Resumo descritivo farmacológico
- 3.Resumo farmacológico em formato tabelar
- 4.Resumo descritivo farmacocinético
- 5.Resumo farmacocinético em formato tabelar
- 6.Resumo descritivo toxicológico
- 7.Resumo toxicológico em formato tabelar
### SUB-MÓDULO 2.7 - RESUMO CLÍNICO
- 1.Resumo dos métodos biológicos, farmacêuticos e analíticos
- 2.Resumo dos estudos farmacológicos clínicos
- 3.Resumo da eficácia clínica
- 4.Resumo da segurança clínica
- 5.Referências
- 6.Sinopses de estudos individuais
