### ISSUE TITLE
Improvement request: Rejection emails to include the overall comment

### ISSUE THREAD

**Issue by jagoje** [openmsupply/conforma-server#724]
Small tweak - not requested

Internal issue prioritised because it's very important in the process (and can be considered as part of other work to be delivered)

Done (on latest snapshot) for:
- [x] U2-OrgRegistration
- [x] U3-OrgJoin
- [ ] ProdRegistration - Screening lvl2
- [ ] ProdRegistration - Assessment lvl2
- [ ] ProdRegistration - Committee lvl2
- [ ] ProdRegistration - FinalDecision

**Comment by jagoje** [comment]
To improve the user experience with the overall comment box.
-----------
Update 1:
Can the following please be added:
The text above overall comment be changed to:
_‘Overall comment
If application outcome is 'Conform': Please use this field to include a summary of the internal decision notes.
If application outcome is 'Request information from the applicant': Please use this field to include a summary of the internal decision notes.
If application 'Non-conform': Please use this field to detail the reasons for rejection to the applicant.'_

<img width="514" alt="image" src="https://user-images.githubusercontent.com/88009219/164971928-b803505a-6951-4a75-a9a2-332fb00996b1.png">

------------
Update 2:

Can the decision radio button for list of questions be amended as follows to help internal staff:
List of questions to _'Request information from applicant. Note: Any non-conforming comments will be displayed to the applicant for actioning."_

**Comment by nmadruga** [comment]
Done for U2-OrgRegistration on latest snapshot

**Comment by nmadruga** [comment]
Not sure if this should be included in this issue... so I'm doing as part of another issue (moving this description into https://github.com/openmsupply/conforma-web-app/issues/1160)

> ## To improve the user experience with the overall comment box.
> Update 1: Can the following please be added: The text above overall comment be changed to: _‘Overall comment If application outcome is 'Conform': Please use this field to include a summary of the internal decision notes. If application outcome is 'Request information from the applicant': Please use this field to include a summary of the internal decision notes. If application 'Non-conform': Please use this field to detail the reasons for rejection to the applicant.'_
> 
> <img alt="image" width="514" src="https://user-images.githubusercontent.com/88009219/164971928-b803505a-6951-4a75-a9a2-332fb00996b1.png">
> 
> Update 2:
> 
> Can the decision radio button for list of questions be amended as follows to help internal staff: List of questions to _'Request information from applicant. Note: Any non-conforming comments will be displayed to the applicant for actioning."_

**Comment by nmadruga** [comment]
After discussed with team on 24/08/2022 it was decided this is not required for ProdRegistration.
