### ISSUE TITLE
Improvement request: Rejection email template - New company registration

### ISSUE THREAD

**Issue by jagoje** [openmsupply/conforma-server#725]

**Comment by jagoje** [comment]
Can the rejection email template please be amended with the following improvements:

1. The date and time is displaying in full format. Can this be amended to just the date. 
<img width="706" alt="image" src="https://user-images.githubusercontent.com/88009219/164972576-1d511cfa-31a9-4e62-a2c8-05432e4e7013.png">

----------

2. After the following text (in the current template) "Após a avaliação da documentação apresentada por você em relação a emrpesa abaixo indicada, sua inscrição foi rejeitada." can the the following be included:

"O motivo da rejeição é o seguinte:
        [Comment from Overall comment box if non-conform was selected]"

**Comment by nmadruga** [comment]
Done on latest snapshot on the drive `angola_2022_08_11_1427`
