### ISSUE TITLE
P1-Template: Dosagem field

### ISSUE THREAD

**Issue by jagoje** [openmsupply/conforma-server#728]

**Comment by jagoje** [comment]
Can the dosage field please be amended to allow for filtering via typing?
Currently it is set to just a scroll drop down.
<img width="656" alt="image" src="https://user-images.githubusercontent.com/88009219/164990215-e3bbe7b2-0b4f-45c2-a7ca-d9b573066150.png">

**Comment by nmadruga** [comment]
That's done (not by me) on latest snapshot ; )
