### ISSUE TITLE
P1-Template: Formulation box

### ISSUE THREAD

**Issue by jagoje** [openmsupply/conforma-server#729]

**Comment by jagoje** [comment]
Two minor things to note :)

1. It would be great to have the "Substância presente no produto acabado?" Field default to Sim.
2. Not sure if possible, but now we are displaying the ingredients lists separately it would be great to either display Tipo as active, or remove the column from being displayed.
<img width="676" alt="image" src="https://user-images.githubusercontent.com/88009219/164993109-c068ba01-d6e1-41ab-8067-2e99204aa9ea.png">

**Comment by nmadruga** [comment]
> Three minor things to note :)
> 
> 1. It would be great to have the "Substância presente no produto acabado?" Field default to Sim.
> 2. Not sure if possible, but now we are displaying the ingredients lists separately it would be great to either display Tipo as active, or remove the column from being displayed.

Final solution:
![Screen Shot 2022-08-18 at 12 52 15 PM](https://user-images.githubusercontent.com/16461988/185268640-7277be32-25da-45b1-bd12-b990b1b14880.png)
![Screen Shot 2022-08-18 at 12 50 19 PM](https://user-images.githubusercontent.com/16461988/185268645-108af970-3a5a-43dc-a3a0-f531ad80ef68.png)

I tried to set the first column "Tipo" with fixed text but it didn't work. So has been removed.

> 3. It would be great the keep the formulation box expanded once you have exited out of the list builder:

Looks better?
![Screen Shot 2022-08-18 at 12 46 00 PM](https://user-images.githubusercontent.com/16461988/185268134-aced734f-4e7e-401d-8efc-e743e46b558a.png)
