### ISSUE TITLE
Carbone template for list of questions summary

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/conforma-server#772]
Part of Epic https://github.com/openmsupply/conforma-web-app/issues/1203

Come up with a Carbone template that can work with any template to dynamically generate a list of questions summary.

- probably only needs to show "Text" field of responses

**Comment by CarlosNZ** [comment]
@andreievg I think I have this sorted now, so I should be able to make this carbone template fairly easily now.

**Comment by CarlosNZ** [comment]
I've included a basic working version of this in the snapshot used for https://github.com/openmsupply/conforma-web-app/pull/1224, so if you select "LIST OF QUESTIONS", you'll get a preview of this PDF.

**Comment by nmadruga** [comment]
> I've included a basic working version of this in the snapshot used for [openmsupply/conforma-web-app#1224](https://github.com/openmsupply/conforma-web-app/pull/1224), so if you select "LIST OF QUESTIONS", you'll get a preview of this PDF.

Exciting!! I was going to have the progress of this - since is one of the remaining to finish Epic https://github.com/openmsupply/conforma-web-app/issues/1203 but it seems you already have done it? I'm going to have another go on testing it today : )

**Comment by nmadruga** [comment]
I have included this Carbone template [loq_generic.odt](https://github.com/openmsupply/conforma-server/files/9366431/loq_generic.odt) in ProdRegistration now and with a small tweak, because the LOQ is generated after a consolidation instead so needed to use `.reviewResponseLink` to get the reviewer level1 comments. It works - almost - something still not good with showing the reviewers' comment. : (

And the query has to be changed to:
````
query getDeclineResponses($reviewId: Int!) {
  review(id: $reviewId) {
    reviewResponses(filter: {decision: {equalTo: AGREE}, and: {reviewResponseLink: {decision: {equalTo: DECLINE}}}}) {
      nodes {
        id
        applicationResponse {
          value
          id
          templateElement {
            parameters
            id
            code
          }
        }
        reviewResponseLink {
          comment
          decision
        }
      }
    }
  }
}
````

**Comment by nmadruga** [comment]
**Problem found for Further Information Requested Carbone template not getting the latest reviews of each element**
As posted in Telegram: 
I have been trying for a while to work on that LOQ Carbone template made for ProdRegistration… And I don’t really see a solution currently. I think it would be good to take some more time to have another look on that. I’m running out of ideas. 

The trouble is: we need to extract the reviewResponses that are meant to show to applicant on each iteration of when the LOQ is sent. That is done using the iterator on the Carbone template which expects a list of only the reviewResponses to be displayed. So there is a query done in GraphQL to get that, it seemed fine. But it is getting ANY Declined review from all of the LOQ iterations. And there is no simple way to solve this. Basically in the Front-end we do a lot of calculations to get this accurate, but how to do that with a simple GraphQL query has been difficult. I’ll set this as pending for now, but I would think a solution using code to update and a field on applicationResponse to easily check if that is part of the latest review done or not would be required….

**Comment by nmadruga** [comment]
Pending approval of PR #831 

Then I'll upgrade the action to get the proper review_responses using the new field `is_latest_review_submission`
