### ISSUE TITLE
Possible bug with user creation

### ISSUE THREAD

**Issue by fergie-nz** [openmsupply/conforma-server#794]
I'm getting a bug when creating new users. Error code on server terminal is "Email sending FAILED: Missing credentials for "PLAIN".
Seems to be independent of the snapshot or branch I'm using.

**Comment by CarlosNZ** [comment]
I think this is probably because you don't have the email credentials in your .env file. I'll show you how to set this up shortly.

**Comment by fergie-nz** [comment]
.env file missing
