### ISSUE TITLE
Bug: Problem keeping template files linked to new versions

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/conforma-server#807]
It's easy to accidentally lose files linked to templates (e.g. .carbone templates) when exporting/importing templates.

When you export a template, the linked files (i.e. matching template_id) get exported with it. That's fine.

And when you import a template, if the linked file doesn't already exist in the system, it gets added. 

The problem is, when you import a template, if the linked file *does* already exist, it gets the id of the *previous* template version, and now the new version no longer has a linked file. And then if you delete the old version of the template, the file gets deleted, too since it's connected to the wrong version.

Possible solutions:
1. always import a new copy of the file regardless so every template version has a linked file. The problem is, we'll need to generate a new uniqueId for it, in which case the actions that refer to it will no longer work.
2. if the file exists, change the template_id to match the new imported template. The downside is, if we re-activate an old version of the template, it'll no longer be linked to the correct file. This is okay if the new version of the template stays in the system, as the file will still exist and it'll connect correctly with the uniqueID. However, as soon as the other version gets deleted, the file will get deleted too.

It seems like Option 2 is the better one, as creating a new uniqueId for a file that has actions/elements that refer to it is a really bad idea. We'll just need to be vigilant and if we ever want to delete a template while keeping an older version in the system, then we'll need to remember to relink the file before deleting the other version.

Any other suggestions?

**Comment by CarlosNZ** [comment]
@andreievg perhaps you can have a look at this as you have a better understanding of the database import process. 

We need the file record to get the "template_id" of the new incoming template record, not its old id. This is probably an exception to the way it works elsewhere, so you might have a better idea how we can achieve what we need?

**Comment by CarlosNZ** [comment]
For now we'll need to manually change the id of the file to match the template id whenever we create/import a new version.

**Comment by andreievg** [comment]
I would assume file is deleted when template is deleted because of cascade on reference in file. I think this reference doesn't quite work since it's linked to template version. How about removing this reference ? 
If we need to keep track of `what` uses a file (i would assume it's either action or form element), we would need to either:

 3. add reference to a file from action land form element
 4. can deduce file use by looking inside action and form element config (for file uuid), already doing something similar in template builder (with `parametersString` exposed on templateElement and templateAction)

And then we can remove files on a schedule (would even add is_carbone_template to file table)

**Comment by andreievg** [comment]
Ohh we also use template_id for `files` to be exported for snapshot of a template, if it's removed this won't work so, a concrete reference on templateElement and templateAction would be the better way to go (3), but it would require a bit of data migration hmm. Do we need to 'delete' templates, can we soft delete them for now:

 5. Soft delete templates

**Comment by CarlosNZ** [comment]
> Do we need to 'delete' templates, can we soft delete them for now

Yes, there are several reasons to delete templates, one of which is [this issue](#799). But also, when in this phase of rapid development, deleting a template and getting all its associated applications, etc to cascade delete is pretty essential to keeping the snapshot tidy and manageable. 

I'm fine to just manually re-link template files for now, just wanted to flag it so everyone remembers to do it.

> Ohh we also use template_id for files to be exported for snapshot of a template, if it's removed this won't work so, a concrete reference on templateElement and templateAction would be the better way to go

We could change the "templateId" in the file table to "templateCode" and just have a "soft" link rather than a proper foreign key. Would require a bit of a change to the snapshot export though, wouldn't it?

Anyway, can be discussed in person at some point, don't think it's super high priority right now (unless there's a simple fix?)

**Comment by andreievg** [comment]
> Anyway, can be discussed in person at some point, don't think it's super high priority right now (unless there's a simple fix?)

I thought removing template_id from file could be, but no it breaks taking snapshot for template. So nope I can't really think of a simple fix

**Comment by CarlosNZ** [comment]
I think the best way to deal with this is to have a trigger function -- whenever a template version is set to "is_active", the function should look for any files linked to that template code and change the reference to the newly activated one. 

I think this is quite important. We'll start seeing problems from it once we start importing new template versions more often (currently we're mostly just updating existing versions).

**Comment by CarlosNZ** [comment]
> I thought removing template_id from file could be, but no it breaks taking snapshot for template. So nope I can't really think of a simple fix

This seems simple and effective, no? https://github.com/openmsupply/conforma-server/pull/938
