### ISSUE TITLE
Allow management access to Lookup tables (and Localisation) without full "admin" access

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/conforma-server#816]
Improving Lookup-tables issue 1: Allow non-admins to edit Lookup tables 

Currently, template builder, snapshots, lookup tables and localisations require "admin" access and are enforced by back-end by being within the "admin" sub-route (which checks for "isAdmin" flag in JWT).

So it's not currently possible to allow access to one of these without granting access to all. Ideally, the lookup tables and localisations control would be considered "management" tasks, so would be accessible to anyone with the "systemManager" permission.

To do this change properly would be a bit of work. Rather than just have a standard "isAdmin" flag marked in the JWT, we'd need to be able to assign specific permissions to specific endpoints, and have additional checking for this in the back-end. 

So we'd probably need to do away with the "admin" sub-route (which checks for "isAdmin" in JWT), and just all endpoints under the main endpoint route ("/api"), and add configurable permissions per endpoint.

So not trivial, but also not a huge amount of work. I'm thinking probably a couple of days, including relevant changes to front-end?

**Comment by nmadruga** [comment]
Good to also remove Admin permission from GrantUserPermission template

**Comment by CarlosNZ** [comment]
Just putting a reminder here -- I've made an additional change to data views to handle a dummy "lookupTables" permission name for matching lookup tables for data views. Just flagging this so we remember to consider it when doing this issue: https://github.com/openmsupply/conforma-server/pull/935#issue-1428733986

**Comment by nmadruga** [comment]
The list of issues to improve Lookup tables includes:

Issue 1: **current**
Issue 2: https://github.com/openmsupply/conforma-web-app/issues/1048
Issue 3: https://github.com/openmsupply/conforma-web-app/issues/1467 - removing the need for exporting first to match IDs

**Comment by CarlosNZ** [comment]
> I'm thinking probably a couple of days, including relevant changes to front-end?

More like an hour and a half 😜 #1040
