### ISSUE TITLE
Move email server config to prefs

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/conforma-server#848]
It's currently part of the repo under the "send_notification" action -> config.json.

I suggest that this be loaded into `applicationData` (back-end) as part of the "environmentData" property, so it's available to all actions (and then can get rid of the plugin's own "config" file).

The only problem with that is there will be no compile-time check for missing config. So the `sendNotification` action will also need to gracefully handle missing email config. I suggest that it should still work (i.e. create the notification), but log a warning in the error_log (and write something to console)

**Comment by CarlosNZ** [comment]
I suggest that this loaded into `applicationData` (back-end) as part of the "environmentData" property, so it's available to all actions (and then can get rid of the plugin's own "config" file).

The only problem with that is there will be no compile-time check for missing config. So the `sendNotification` action will also need to gracefully handle missing email config. I suggest that it should still work (i.e. create the notification), but log a warning in the error_log (and write something to console)

**Comment by CarlosNZ** [comment]
@fergie-nz I think this might be a good one for you to have a go at. Let me know if you need anything explained to you.

**Comment by fergie-nz** [comment]
Is this what you had in mind? I've brought the email config over to be called as environment data. However it is still static.
