### ISSUE TITLE
Bug: App breaks when Re-assigning section after review has already started

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/conforma-server#860]
I have found this bug while testing the Re-assignment of section in Stage 1 of latest snapshot. You can try using the following steps (and latest snapshot):
1. Log in as `jess` and go the Assigning page of: http://localhost:3000/application/AIM-2022-0059/review?tab=assignment
2. Assign all sections to Nicole Madruga. 
3. On another **incognito tab** log in as `nicole`, and start the review
4. Back to user `jess` re-assign all sections to yourself
  * You would need to click Re-assign of each section and selection "Usuário atual" and at after that click the button "Aplicar"
  * Tedious, I know...
5. This was causing a problem when trying to reload Nicole's user review page... But now it seems the problem isn't happening!

I see this on the logs, which is what should be happening. This somehow was failing before and causing the `review_status_history` have 2 entries for status DISCONTINUED and both were is_current = true!

![Image](https://user-images.githubusercontent.com/16461988/190934032-0252f415-750f-4a46-ba98-6d44ba8ef24f.png)

**Comment by CarlosNZ** [comment]
I think this should be sorted
