### ISSUE TITLE
The problem with custom-structured response data in data tables

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/conforma-server#864]
## The Problem

We store much of the output from an application in the same "shape" as the original application response rather than simple text values. The advantage of this is that we can use exactly the same element to display it in the outcome table and make it look pretty, like so:
![Screen Shot 2022-09-22 at 2 04 38 PM](https://user-images.githubusercontent.com/5456533/191642272-0b103f76-3ef5-4735-9c8f-08a6110b53b1.png)

Other advantages include simple mapping from application form to a single field in the database record.

However there are disadvantages to this:
- it's hard to do more with the data, e.g. Filtering, searching, etc.
- it's difficult to extract specific bits of information from within, particularly when there is an arbitrary number of values, or a complex display structure
- the information is not structured in a way that we would if we were just saving the entity itself. The properties in the response are specific to the *display* element, not the data itself
- it's difficult for other software (e.g. CSV output) to parse in a meaningful way, particularly when every instance of it can be differently structured.

The good news is that most fields are stored as "simple" data types (mainly "text", but a few numbers and dates). It's only really *lists* of things that need to be captured differently.

In particular the most complex response shape is the list builder, as it can have an arbitrary number of other elements contained within it (including other list builders!) The most complex example of it is the "Formulations" response in Product Registration, which as an unlimited number of formulations, each of which has its own lists (of arbitrary length) of active and inactive ingredients.

Here is an example of a single "Formulations" response:

https://gist.github.com/CarlosNZ/42241b213ba4470a74868d0e704bd534

## Use cases possibly affected

In order to know how best to handle the problems caused by this kind of structured data, we need to have a clear understanding of what is required. As far as I can tell so far, these are the main two use cases we need to consider:

- Filtering/searching by deeply nested data in the Data View tables
- Outputting a list of data records as a CSV file (from Grafana)
- Displaying records nicely in Grafana (this might not be necessary if we can get enough functionality into the Data Views in the app)

Please describe any additional considerations, and add further detail to the above and give examples of specific usages of them we might encounter.

## Possible solutions

It's hard to know exactly what the best approach would be, and each of those use cases above probably require a different solution.

Also, none of the ideas listed here would provide a comprehensive solution for all types of complex data -- in particular the formulations list is particularly gnarly.

With that in mind, here a few possible ideas of ways to mitigate the above problems:

- output multiple versions of the same response data into different columns for data output records. E.g. for a "generic ingredients" list, we might output the full response for nice display in the DataView table, and a plain text output (concatenation of ingredient names) in another field, which would allow searching, and even another field containing more appropriately "structured data"[^1] for other software to parse.
- each complex plugin, such as listBuilder or search could come with its own transformation "script", which would allow us to configure exactly how to convert the response data in to something more useful
- just write custom one-off SQL queries for searching or exporting complex JSON data when required. (This would be the easiest if we don't need to do it too often.

Add other ideas here (or more detail for the above).

[^1]: By structured data, I mean structured in a way that is more appropriate to the entity itself, rather than the "response shape", which is structured for a specific display element. E.g. an array of objects with simple properties for an ingredients list, or a manufacturers list: `[ {name: "Mega Chemicals", function: "manufacture"}, {name: "NZ Fabricators", function: "packaging"}] `

**Comment by jagoje** [comment]
This is great Carl!

I am open to all of the above solutions. I think a good initial approach is the output multiple versions option. I know it is not the most generic, but it will be good for any of the planned implementations. 

I have gone through the form, and can confirm that the only fields that are not text outputs that should be searchable/viewable in Grafana are:

### AIM Database: 

Generic active ingredient names we could store the generic name as a text string like : Active ingredient 1 + Active ingredient 2 etc. 

**Note 1:** Reason for this field choice - unlike formulation list builder this field is singular. 

Manufacturer name: This one is trickier. This field is different in the 50008 instance compared to our base version. However, the following principles apply to both. All manufacturers related to the product should be searchable, it is enough to search by name.  

**Note 2:** At minimum it would be important to search/filter by the Finished product manufacturer (this is specified) in processing steps/field.

### Company database:

Entity function (e.g. Distributor, manufacturer etc.)

Not sure what this part was:
_"Just write custom one-off SQL queries for searching or exporting complex JSON data when required. (This would be the easiest if we don't need to do it too often."_

But I think that it would be great to be able to export a csv from Conforma - I think this is a good approach eventually! 

--------------------------
**Note 3:** For reference, the following I would consider a comprehensive set of default filters for any product table:

- Registration number
- Origen
- Entity 
- Name of medicine
- Generic active ingredients
- Therapeutic Category
- Manufacturer name
- Dosage Form 
- Route of administration

**Comment by CarlosNZ** [comment]
> **Manufacturer name:** This one is trickier. This field is different in the 50008 instance compared to our base version. However, the following principles apply to both. All manufacturers related to the product should be searchable, it is enough to search by name.
> 
> ****

One question -- would you want to search by multiple names in the same query? A simple text match would be simplest to implement, but it means that you couldn't search multiple names at once. 

If we do want to search multiple, we should be able to do it just by allowing multiple filters of the same type to be added. So you'd add a "manufacturer name" filter, and enter "Manufacturer 1" (or part thereof), then add *another* "manufacturer name" filter and enter "Manufacturer 2".

Sound okay?

**Comment by jagoje** [comment]
Yes - searching for multiple would be great, especially for active ingredients. but manufacturers I can see being helpful as well. 

That approach sounds good to me

**Comment by CarlosNZ** [comment]
This problem is basically solved now, with the Data View filtering functionality :)
