### ISSUE TITLE
Rejection decision at Screening stage, reflects within the Technical Assessment page in the UI

### ISSUE THREAD

**Issue by jagoje** [openmsupply/conforma-server#888]
It was noticed during UAT on the 5/10/22 that when a rejection decision was taken during the screening stage, that this was incorrectly reflected in the UI to show it had been rejected at the Technical Evaluation stage. 

![Image](https://user-images.githubusercontent.com/88009219/194180125-5aa8495f-db72-4711-b710-3b4b082bc943.png)

**Comment by nmadruga** [comment]
Done in `angola_2022_10_07_1400` snapshot
