### ISSUE TITLE
Create backup script and scheduler (using new pg_dump script)

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/conforma-server#912]
Part 3 of Epic #909

**Comment by craigdrown** [comment]
Hi @CarlosNZ  - @Chris-Petty  has already done Postgres export with backup to Backblaze - is this work based on that?
I can't see the point of encryption if the output is on the same volume as the original db?
Backblaze handles encryption for us for off-site.

**Comment by CarlosNZ** [comment]
@craigdrown 

Thanks, it's not just Postgres export, though, it's the whole system, which includes database, files, prefs, localisations. 

We already have a "snapshot" system for this, so we've just made some improvements here to make it faster and more suitable for backups. 

Regarding encryption: the idea was  the backup snapshot is exported to a folder which would be a cloud sync folder e.g. Dropbox (it could also be Backblaze, but the key thing is the cloud sync setup is configured independent of Conforma). So even though the folder is on the same system locally, it could be being synced to anywhere. @dhanya thought some security would be important (for Fiji) as these backup archives could end up anywhere. (Summarised in #881)

Anyway, it's fairly simple to encrypt the archive zip, but it's not required -- if you don't provide a password (in environment variables--it's never stored as text) then the .zip won't be encrypted.
