### ISSUE TITLE
UAT Feedback Config Changes

### ISSUE THREAD

**Issue by jagoje** [openmsupply/conforma-server#923]
Priority config work to do from UAT feedback for AIM template.

**Comment by jagoje** [comment]
1. After all that discussion they would like us to make ALWAYS modules 1-5 visible. 
So can we please remove this field (would be good to keep the code just in case).



![Image](https://user-images.githubusercontent.com/88009219/197031896-0f6053c3-8c2f-42a0-a6df-bf4b0d18d311.png)

**Comment by jagoje** [comment]
2. Can this field please be defaulted to display 'Sim' (if radio button not possible swap to drop-down)


![Image](https://user-images.githubusercontent.com/88009219/197032069-5b0d33ba-2f84-4173-bd7c-845f7d78b24b.png)

**Comment by jagoje** [comment]
3. Change this heading to ⁃ 2.2.1. Forma farmacêutica e apresentaçã


![Image](https://user-images.githubusercontent.com/88009219/197032419-e885d618-3a15-413c-aa48-8d441370225b.png)

**Comment by jagoje** [comment]
4. Update in the submission email 10 days to 7 days.



![Image](https://user-images.githubusercontent.com/88009219/197032958-bd97f4e4-aa14-4c80-8800-92ebb3015e9e.png)

**Comment by fergie-nz** [comment]
> After all that discussion they would like us to make ALWAYS modules 1-5 visible.
So can we please remove this field (would be good to keep the code just in case).

I'll set this to default 1-5, then hide the field. Saves a lot of time and easy to switch back if they change their mind.

Otherwise it is very slow to make any changes if they do want to go back.
