### ISSUE TITLE
Problem to assign applications created before creation/granted permission to assigner users

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/conforma-server#926]
Apparently some applications were created before some assigner users were added or perhaps the permissions to assign the Review on the first stage. An attempt to run-action `refreshReviewAssignments` that should generate all reviewAssignment and ReviewAssignmentAssignerJoins for existing applications was run, but even though it shows SUCCESS the reviewAssignmentAssignerJoins were not generated and the assigners still can't see the Assignment page. : (

![Image](https://user-images.githubusercontent.com/16461988/197669378-234e0db9-2ef6-404c-a8ae-4e49dfb2646d.png)

**Comment by CarlosNZ** [comment]
![Screenshot 2022-10-26 at 12 28 27 PM](https://user-images.githubusercontent.com/5456533/197900696-78a058ea-9c94-41f6-a2f5-cc95bc2bcf9e.png)

It's showing this label, but issue is still open. @nmadruga can you confirm which is correct here?

**Comment by nmadruga** [comment]
Oops! I should have closed it after that : )

**Comment by nmadruga** [comment]
Oops! I should have closed it after that : )
