### ISSUE TITLE
Bug: Rejection at triage appears as rejection at Technical assessment

### ISSUE THREAD

**Issue by jagoje** [openmsupply/conforma-server#927]
![Image](https://user-images.githubusercontent.com/88009219/197736199-08b53048-706f-431b-84ab-0bad944fbc19.png)

**Comment by jagoje** [comment]
Screenshot above.

**Comment by nmadruga** [comment]
Fixed in snapshot `angola_2022_10_27_1151`, please note: P1-ProdRegistrationLong has a  **New version**, so existing applications won't have the fix added. I can do this, but thought it would be best to remove existing applications before next UAT
