### ISSUE TITLE
Fiji testing day - Trigger error after self-assignment

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/conforma-server#947]
Trigger issue, after self assigning review for join registered company, can access review home page: This is reproducible, had this on second application to join company 
Found by Clemens.

**Comment by CarlosNZ** [comment]
I'm guessing config?

**Comment by nmadruga** [comment]
Probably! I'll have a look (after I finish looking at https://github.com/openmsupply/conforma-templates/issues/76)

**Comment by nmadruga** [comment]
Looking into this problem now

**Comment by nmadruga** [comment]
Done in snapshot `Fiji_2022_11_04_1200`

**Comment by CarlosNZ** [comment]
> Done in snapshot `Fiji_2022_11_04_1200`

Awesome! 👏👏👏 Glad it was a config thing.

**Comment by nmadruga** [comment]
Ok - there is another problem that I haven't seem before. So I'll continue checking what's wrong.

Basically the other problem is to start a Review. After you select yourself as the assignment and when you click Start:
![Screen Shot 2022-11-04 at 3 38 15 PM](https://user-images.githubusercontent.com/16461988/199879984-a13c3262-4561-4695-9ecd-977474f319ab.png)
I click start and it fails, that’s probably the same one Andrei was saying he saw. And it’s not related to unassignment
![Screen Shot 2022-11-04 at 3 38 11 PM](https://user-images.githubusercontent.com/16461988/199879988-78563fb1-8ba0-4625-a182-9c050e767e66.png)
