### ISSUE TITLE
Simplify the "locking" of reviews by moving logic into the database.

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/conforma-server#956]
It's becoming increasingly problematic to try and figure out all the logic for the "is_locked" field of both "review_assignment" and "review" as part of the "generateReviewAssignments" and "updateReviewStatuses" actions, so we are proposing to remove all considerations of "is_locked" completely from the actions and handle it all in the database before the trigger even gets written.

The "is_locked" value has no affect on back-end operations, it's purely for the front-end to be able to determine whether to show something as assignable, so should be fine to keep it completely out of actions.

First step:
- get rid of the "is_locked" field on the "review" table. This can be derived from the "is_locked" field on review_assignment and it makes it a lot simpler to only have to keep one field updated (not to mention consistent). I don't think there is any reason where these two values would need to be different, so may as well just have one. 

Then add additional triggers that run BEFORE updates on "application" and "review", so they'd update the appropriate records with the locked status before the normal action trigger runs.

Logic would be like this:

**ON_REVIEW_SUBMIT**:
(i.e. updating a "review" record with trigger "ON_REVIEW_SUBMIT")
- If `decision !== LIST_OF_QUESTIONS` or `is_last_level !== true`, do nothing. (i.e. they both must be true to continue)
- Find all review_assignments for the same stage/level ~~that are "ASSIGNED"~~ and set them to "is_locked"

**ON_APPLICATION_SUBMIT**:
(i.e. updating application record with trigger "ON_APPLICATION_SUBMIT")
- all review assignments associated with this application to `is_locked: false` (doesn't matter about level or stage, just do all)

There's one more case to consider, and that's *new* review assignments created as a result of actions triggered by the above events. In the "ON_REVIEW_SUBMIT" case we don't need to do anything, as only next-level review assignments could be created, and they should be all unlocked.

For application submissions, the only new ones created would be if new reviewers have been added or existing reviewers have new permissions. So we probably also need to add a "ON INSERT" trigger to the review assignment table to update the "is_locked" fields based on the above logic.

Is that all?

**Comment by nmadruga** [comment]
> * Find all review_assignments for the same stage/level that are "ASSIGNED" and set them to "is_locked"

Well, not sure if this is only for **Assigned** reviews, since we can still Re-assign some un-submitted review to another person and at that point the new ReviewAssignment would be unlocked.

**Comment by nmadruga** [comment]
> * all review assignments associated with this application to `is_locked: false` (doesn't matter about level or stage, just do all)

Should we check if the Application latest Review has status of "LIST_OF_QUESTIONS" too? The case where I see this failing is: we run the action ON_APPLICATION_SUBMIT to test something else and that unlocks reviews but they should be kept as locked until the Application has corrected and re-submitted. Maybe I'm wrong, and RE-SUBMITTING implies the applicant has given back the token to Reviewers

**Comment by CarlosNZ** [comment]
> Should we check if the Application latest Review has status of "LIST_OF_QUESTIONS" too? The case where I see this failing is: we run the action ON_APPLICATION_SUBMIT to test something else and that unlocks reviews but they should be kept as locked until the Application has corrected and re-submitted. Maybe I'm wrong, and RE-SUBMITTING implies the applicant has given back the token to Reviewers

I think re-submitting means make it available for (all) reviews. Not sure what you mean by "to test something". What situation are you thinking of?

> Well, not sure if this is only for **Assigned** reviews, since we can still Re-assign some un-submitted review to another person and at that point the new ReviewAssignment would be unlocked.

Right, so we probably need to run the "review_assignment" trigger I described for updates as well.

**Comment by CarlosNZ** [comment]
Okay, thinking about this some more -- it occurred to me that the "locked" status is actually something that applies to ALL reviews at the same time -- they're either all locked (i.e. can't submit) or unlocked (can submit). Therefore it seems crazy to have to update all the review and review_assignment records with this information when it could just be stored in a single place for each application. And the logic to determine what *new* assignments should be is completely unnecessary.

What I suggest is adding a boolean column to the "application" table called "is_review_submittable", which just gets turned on/off (true/false) as appropriate.

The job of keeping this flag updated should be in the `changeStatus` action, since whether a review is submittable or not depends on the application status -- if its LOQ, then can't submit review, otherwise you can. This would be a very simple addition to the changeStatus action, and we could then pull everything related to "is_locked" out of the other actions (which is a whole lot of very messy logic).

To avoid minimal disruption to the front-end, I suggest adding a GraphQL computed column field to the "review" table, so the "locked"/"submittable" status of each review can still be queried as it is now (mostly).

**Comment by CarlosNZ** [comment]
Okay, maybe it can be even simpler than that. We just derive "is_locked" straight from the current application status:

- CHANGES_REQUIRED / DRAFT ==> is_locked = true
- Anything else ===> is_locked = false

So the "is_locked" field of "review_assignment" can just be a computed column that returns true or false based on a simple function that checks the application status as above.

Am I crazy or can it just be that simple, @nmadruga ?

**Comment by nmadruga** [comment]
> So the "is_locked" field of "review_assignment" can just be a computed column that returns true or false based on a simple function that checks the application status as above.
> 
> Am I crazy or can it just be that simple, @nmadruga ?

That sounds good - as per our in person conversation. Although I'm thinking what should we do regarding the `review.is_locked`? would we have it there as well, or would we return the `reviewAssignment.is_locked` to the front-end?

**Comment by CarlosNZ** [comment]
I'm thinking we just have a single computed column on "review" table -- "is_locked".

No point keeping it on review_assignment, as that only existed to specify for reviews before they're created, but with this we'll be able to have accurate is_locked status anyway.

It also means the ENUM "review_status" will have to drop the "LOCKED" status, but that seems worth it.

Will need to update the front-end accordingly.

**Comment by nmadruga** [comment]
Great! Sounds good to me Carl : )

**Comment by nmadruga** [comment]
Ok to close this one now @CarlosNZ? Or would you like to keep it open until we have the `feature/final-decision-fixes` branch merged?

**Comment by CarlosNZ** [comment]
Yeah, I'll close it. Thanks
