### ISSUE TITLE
Bug: Snapshot import missing all applications 😭

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/conforma-server#957]
On branch `feature/final-decision-fixes` related to a fatal CASCADE drop in migration code. Easy fix apperantly!

**Comment by CarlosNZ** [comment]
Hey @nmadruga, I'm having trouble reproducing this. All my applications are still intact after snapshot load.

Have tried with `1413B-fix-stage-number-in-review_response` and `feature/final-decision-fixes` branches.

Can you send me the snapshot that is not loading properly? And name the branch? Any other pertinent conditions?

**Comment by CarlosNZ** [comment]
@nmadruga Can you please see if you can reproduce this, and if not, please close the issue? Thanks.

**Comment by nmadruga** [comment]
No, I haven't seen this happening anymore! I'll close now
