### ISSUE TITLE
Bug: Problem keeping category when importing template

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/conforma-server#967]
![Image](https://user-images.githubusercontent.com/5456533/202278896-b42d0ba3-2ae0-4459-a0ab-11c854ef692a.png)

Gets reset to "No category".

This was caused by the change I introduced the other day to fix file import:

```
        if (referenceValue) foreignKeyReplacements[columnName] = referenceValue
        else foreignKeyReplacements[columnName] = null
```

The `else...null` line was added. 

Unfortunately, there's no simple way to fix one problem without causing the other, as there's no clear way to know if the inserted reference for an existing record (i.e. not being imported with the template) is correct in the database or not.

I'm considering adding a check to the `findReferenceValues` function to look for existing records in the database if not found in the "insertedRecords", but this could cause problems if the foreign key exists, but refers to a different item than it did in the database that it was exported from. (i.e. the category could change to the wrong one without anyone noticing).

There are so many little bugs and problems like this which support my belief that the template import/export system needs to be completely be re-written. The problem has always been trying to treat it like a "snapshot" rather than its own special case. (Links should be matched more by name and code rather than foreign key references IMO, with additional logic to handle conflicts.)

Obviously that's quite a big job, so not suggesting doing it right away, but we just need to remember that template import/export will remain buggy while it works the way it does now.

Not sure what the best solution to this immediate problem is. If we have to choose between templates not importing their linked files, and templates being imported with missing categories, I think the latter is preferable as its easier to notice and fix. (In which case, we'd leave it as it is now and just have to manually re-add the category when importing templates). 

Do we agree? (Or does anybody have a better solution?)

**Comment by nmadruga** [comment]
> Links should be matched more by name and code rather than foreign key references IMO, with additional logic to handle conflicts

Yes. I had the same thought while reading about the problem explanation at the beginning of this issue description...

**Comment by nmadruga** [comment]
> (In which case, we'd leave it as it is now and just have to manually re-add the category when importing templates).
> 
> Do we agree? (Or does anybody have a better solution?)

I think that's all good to wait too, if this only affects categories.

Would you know anything else that could be affected by this? Dashboard filters? Template stage or elements? Permissions?

I know that the fix when this was introduced was to fix the files (Carbone files to generate correspondence with Applicant in action `generateDoc`) so that I understand as would be safe.

**Comment by CarlosNZ** [comment]
> Dashboard filters? Template stage or elements? Permissions?

There are all exported along with the template, so the existing import functionality is able to relink them to the correct ones. The problem is with items that *aren't* exported -- it's hard to re-link to existing records in the database (cos even if we look them up to check the id exists, there's no way to know that it's actually the same item)

Having said that -- maybe we can just export the category along with the template. Let me look into that...

**Comment by CarlosNZ** [comment]
> Having said that -- maybe we can just export the category along with the template. Let me look into that...

Nope, doesn't work. Cos "template_category" has no FK ref to "template", it's the other way round.

**Comment by nmadruga** [comment]
Maybe a simple solution would be to generate a join table `template_category_join` in order to export categories with templates....

**Comment by CarlosNZ** [comment]
> Maybe a simple solution would be to generate a join table `template_category_join` in order to export categories with templates....

Yes, but that's a decent amount of work in itself and I'd rather just fix the problem. That falls into the "plugging holes to make up for poor design choices" category of solution. I'm always much more in favour of "fix the actual bad design" solutions, even if they take longer.

(But not for now, alas 😔)

**Comment by CarlosNZ** [comment]
> Nope, doesn't work. Cos "template_category" has no FK ref to "template", it's the other way round.

Hang on a sec, it manages to export/import "permissionNames" correctly, even though there is no FK ref to template in permission_name table, so there must be a way to do the same thing with categories.

Let me investigate...

**Comment by CarlosNZ** [comment]
> Hang on a sec, it manages to export/import "permissionNames" correctly, even though there is no FK ref to template in permission_name table, so there must be a way to do the same thing with categories.
> 
> Let me investigate...

Okay, I think I know how to fix this.
