### ISSUE TITLE
Review history is being recorded out of order / has multiple records.

### ISSUE THREAD

**Issue by fergie-nz** [openmsupply/conforma-server#974]
![B838CB51-16B9-4F4B-8EC2-D380FB686FFD](https://user-images.githubusercontent.com/90807420/203659557-0fa080ec-7e3b-4cb6-a80f-d6fa7e2d2dca.jpeg)

In this case "bad name" was being recorded despite this not being submitted.
Also out of order with the application history.

This occurs when viewing review history of applications which have had changes requested on the latest Angola snapshot  and Angola live server

**Comment by CarlosNZ** [comment]
Pretty sure this was fixed.
