### ISSUE TITLE
Proposal for keeping "core actions" out of template configs

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/conforma-server#975]
There are a number of actions that *must* run on certain events in order for the system to function correctly, and it's kind of a hassle to make sure they're correctly configured on every template, and too easy to accidentally misconfigure them and break things.

These should really be hard-coded into the system so we don't have to worry about them at all in configs. I suggest adding an extra function in `processTrigger` to insert these "core" actions into the "actionsSequential" sequence. The position in the sequence and the exact parameters might vary somewhat, so there would need to be a hard-coded reference for how to insert the actions into the sequence.

We shouldn't try and do this until we've identified all the core actions, what events they run on, where in the sequence they need to go (some might actually be async?), and what parameters they take (and how to configure them?), so let's start making a list here.

I think this will actually be quite easy to implement, the hard part will be identifying and specifying the details for what the actions are, so let's start a comprehensive list here:

### ON_APPLICATION _CREATE
- `generateTextString` for serial. We need a way for the "pattern" parameter to be configurable, the rest can probably be hard-coded (as per the current "CoreActions" config in core_templates). Perhaps we need a simple "pattern" field in the template builder (with a default)
- `generateTextString` for application name. Just use the "CoreActions" config (names it `<templateName> - <serial>`). If a different name is needed
- `incrementStage` -- simple :) 

These should all go *before* any custom actions that might be added to the template.

### ON_APPLICATION_RESTART
- Change status (as per core templates)

### ON_APPLICATION_SUBMIT
- `changeStatus` to SUBMITTED. Easy
- `Trim duplicate reponses` as per "CoreActions"
- `generateReviewAssignments` as per "CoreActions"
- `updateReviewStatuses`  reverting as per https://github.com/openmsupply/conforma-templates/issues/106
- `cleanupFiles` as per "CoreActions"
- MAYBE "Change Outcome" IF can find condition that considers reviewability?

### ON_REVIEW_ASSIGN
- `changeStatus` "On Re-assignment if review is existing change to DRAFT"
(For case when someone is re-assigned and they have an existing review -- should go back to DRAFT)

### ON_REVIEW_CREATE
- `changeStatus` - review status to "DRAFT"

### ON_REVIEW_RESTART
- as per core templates (Sets to DRAFT)

### ON_REVIEW_SUBMIT
- `changeStatus` -- review status to "SUBMITTED"
- `trimResponses` -- as per "CoreActions"
- `updateReviewStatuses` (as per discussion)
- `generateReviewAssignments` (no condition or parameters necessary)
- `updateReviewVisibility` -- as per core_templates, including Condition
- `incrementStage` -- core if and only if is last level and CONFORM
- `changeStatus` -- change application to "CHANGES REQUIRED" if last level and decision is LOQ
- `changeOutcome` -- Maybe? (But sometimes we need if for "Application Submit")

### ON_REVIEW_UNASSIGN
- change existing review status to "DISCONTINUED"

Any other triggers?

## Summary

It seems like all the "core" actions should be inserted *before* any template-specific actions run, which makes it easier. And as far as I can tell, the only one that would require any configuration is the very first one (pattern for generate Serial string), so we'd just need to come up with a solution for this -- my suggestion is just a simple "serial pattern" field in the main template builder config (and probably a new field on the "template" database table to store this).

I think this would make things a lot better for multiple reasons:
- maintaining these actions would be easy -- any changes just need to be done in one place in the code base with no changes done to template configs
- safer -- it would be very difficult to break functionality by misconfiguration actions
- the template builder Actions page would be a *lot* less crowded and therefore much easier to work with and maintain

**Comment by CarlosNZ** [comment]
One other thing to do as part of this: add some logic to "useSnapshot" and don't allow snapshots created with versions older than 0.5.0 to be loaded. (We already check that the snapshot version is not newer than current version, so this can be included there)

**Comment by nmadruga** [comment]
> * set status to "DISCONTINUED" (a bit unclear about this)

Used for when someone was assigned a review and started - after being unassigned the `review.status` is changed to DISCONTINUED. So the user can no longer submit, even though is still accessible. And if this review is Re-assignment to this same user, the existing `review.status` is set back to DRAFT by this action:

> changeStatus "On Re-assignment if review is existing change to DRAFT"

**Comment by nmadruga** [comment]
@CarlosNZ Is this one Ready for review?

**Comment by CarlosNZ** [comment]
> @CarlosNZ Is this one Ready for review?

It's ready in a conceptual sense. 

The only thing that's not done is figuring out exactly *what* the core actions should be. 

But I thought we could go through that together at some point and get it really solid.

**Comment by CarlosNZ** [comment]
Done
