### ISSUE TITLE
Re-write "Update Review Statuses" action

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/conforma-server#977]
Fixes https://github.com/openmsupply/conforma-templates/issues/106

As per discussion [here](https://github.com/openmsupply/conforma-templates/issues/106)

We will incorporate this into [core actions](https://github.com/openmsupply/conforma-server/pull/976) once it's done, so please base this work off the `feature/core-actions` branch and we'll get everything working nicely before merging it together (and updating the snapshots accordingly)

@nmadruga -- assigning you as I think you're already made a start?

---

From discussion on other issue:

> As far as I can tell, it should do the following only:
> 
> - find any reviews linked to the current application stage/level that have "changedResponses" within the "assigned_sections" of the linked review_assignment and change their status (add new review_status_history) to "DRAFT"
> 
> Is that correct? (Maybe I'm missing something else?)
> 
> - single query to get reviews/review-assignments (don't consider sections)
> - bit of logic to filter out reviews whose assigned_sections don't overlap with the "changedResponses"
> - update the review status for those reviews (just call the existing "changeStatus" action on each one -- don't write additional logic or queries)
>

**Comment by CarlosNZ** [comment]
Okay, @nmadruga, as discussed, here is the summary of the logic required here. Please let me know if you agree:

- ON_APPLICATION_SUBMIT:
  - For all Level 1 "SUBMITTED" reviews that have sections that have changed responses, set status to "PENDING"
  - For all Level 2+ reviews (that are SUBMITTED or DRAFT), set status to PENDING (we're assuming there can be only 1 review for higher levels, since they get assigned all sections)

- ON_REVIEW_SUBMIT:
  - Set higher level reviews to "PENDING". (This should cover cases when reviewer is reviewing new applicant changes AND when they themselves have had to change an existing review before sending back to applicant)

Does that sound right? Is anything missing?

**Comment by nmadruga** [comment]
> * For all Level 2+ reviews (that are SUBMITTED or DRAFT), set status to PENDING (we're assuming there can be only 1 review for higher levels, since they get assigned all sections)

This one is not accurate. We should keep Level 2+ as is. They would only change after one of the PENDING Level 1 review submits...

**Comment by CarlosNZ** [comment]
> This one is not accurate. We should keep Level 2+ as is. They would only change after one of the PENDING Level 1 review submits...

Okay, so just remove that?

**Comment by nmadruga** [comment]
> ON_REVIEW_SUBMIT:
> 
> * Set higher level reviews to "PENDING". (This should cover cases when reviewer is reviewing new applicant changes AND when they themselves have had to change an existing review before sending back to applicant)

> Does that sound right? Is anything missing?

Yes. Missing that one:

ON_REVIEW_SUBMIT:
* Set higher level reviews to "PENDING". (This should cover cases when reviewer is reviewing new applicant changes AND when they themselves have had to change an existing review before sending back to applicant)
* Set lower level reviews reviews that have sections that have changed responses to "CHANGES REQUIRED" when higher level review submits with this decision.

**Comment by CarlosNZ** [comment]
> Set lower level reviews reviews that have sections that have changed responses to "CHANGES REQUIRED" when higher level review submits with this decision.

Cool. So one thing I'm not totally clear about is what we mean by "changedResponses" here. In this action the "changedResponse" input refers to the review/application being submitted. But for a higher-level review, does the "changedResponses" (that gets generated by the "trimResponses" action) mean responses for which the current reviewer has requested changes? (That's a slightly different thing to the normal "changedResponses" isn't it?)

**Comment by nmadruga** [comment]
> mean responses for which the current reviewer has requested changes? (That's a slightly different thing to the normal "changedResponses" isn't it?)

Yes, it means reviewResponses that were Rejected. And yes, a bit different from what is done for when we change to PENDING after the ON_APPLICATION_SUBMIT event. But I believe that's what the action updateReviewStatuses used to do

**Comment by CarlosNZ** [comment]
> ON_REVIEW_SUBMIT:
> 
>     * Set higher level reviews to "PENDING". (This should cover cases when reviewer is reviewing new applicant changes AND when they themselves have had to change an existing review before sending back to applicant)

Sorry @nmadruga just one further clarification here. When I've said "higher level reviews", should it be "the NEXT level reviews" or "ALL higher reviews"? (Of course this only makes a difference if there is more than 2 levels, but it'd be good to be precise)

**Comment by CarlosNZ** [comment]
Closed by #980
