### ISSUE TITLE
Bug: When submitting one review it's been changed to PENDING

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/conforma-server#985]
This is when using `feature/core-actions` branch, so only reporting a bug to be fixed prior to pre-release.

After the review is submitted the message is displayed (In Portuguese due to localisation)
<img width="758" alt="Screen Shot 2022-12-02 at 11 40 13 AM" src="https://user-images.githubusercontent.com/16461988/205205879-fe6bc5fd-e6c4-412c-99c2-7ef8df715665.png">

After that happens there is a "Reavaliar" action for the level 1 reviewer that just submitted
![photo_2022-12-02 16 11 59](https://user-images.githubusercontent.com/16461988/205206651-c8ce13c7-3a13-4bf7-a817-c3c9ae5131b1.jpeg)

Basically displaying in the wrong moment - due to a change on status that shouldn’t have happened. I can investigate that in 30 minutes if someone else isn’t looking.

It is supposed to show when working on a consolidation and the lower level review submits, so new responses will be added to your review. So the message says: “You will need to refresh your page"

**Expected Result:**
Should be only changing other reviews ON_REVIEW_SUBMIT if:
- lower level reviews in case a reviewer (of last level) submits a review to get changes from lower level reviewer.
- higher level reviews in case it has started and a new lower level reviewer submits some more work

**Comment by CarlosNZ** [comment]
> After that happens there is a "Reavaliar" action for the level 1 reviewer that just submitted

I'm not sure what this is referring to. The problematic action should be in the core actions, so where is that screenshot from?

> * lower level reviews in case a reviewer (of last level) submits a review to get changes from lower level reviewer.
> 
> * higher level reviews in case it has started and a new lower level reviewer submits some more work

Which one is not correct in this case?

**Comment by nmadruga** [comment]
> I'm not sure what this is referring to. The problematic action should be in the core actions, so where is that screenshot from?

Thanks! I fixed the screenshot now

> Which one is not correct in this case?

Both are correct. But the current review is getting updated too - it shouldn't be since it's none of those cases.

I'm about to test my change to create a PR to fix this

**Comment by CarlosNZ** [comment]
> Both are correct. But the current review is getting updated too - it shouldn't be since it's none of those cases.

Ooooh, I see. That's better, should be pretty easy to fix then. (Probably just needs "UpdateReviewStatuses" to explicitly exclude the current review from query results, guess I forgot about that case)
