### ISSUE TITLE
Bug: issue with TrimResponses core-action firing on PasswordReset template which prematurely deletes password fields.

### ISSUE THREAD

**Issue by fergie-nz** [openmsupply/conforma-server#988]
Update password stuck. 

Where:
- when using the feature/core-actions branch
- Any user which resets their password when a default value for password field isn't entered

Trim responses fires on the initial application submit, which deletes password fields.

Adding a default value as anything works around this in config, as it prevents Trim Responses deleting empty fields.

Proper fix might involve allowing trim responses to not activate on this particular form.

**Comment by nmadruga** [comment]
Thanks for reporting that Ferg! I'll have a look on this today and report on this issue.

**Comment by fergie-nz** [comment]
Leaving open for now until a proper fix can be done, as this will likely come up for any new snapshots which are created

**Comment by CarlosNZ** [comment]
> Just a note: we have currently "fixed" this problem on PasswordReset template in Angola server by adding a `defaultValue` on this elementPlugin, which prevents it from being deleted by TrimResponses action

This seems like a good solution and a good use case for the "defaultValue" field (at last!!!)

However, I just checked the latest Angola snapshot (on 50008), and there is nothing actually set for the "defaultValue" in that field. Should there be?

**Comment by CarlosNZ** [comment]
> Proper fix might involve allowing trim responses to not activate on this particular form.

Yeah, I'd like to be able to do it without hard-coding a particular template code into the core actions though (cos it might be different for different installations, and also it might not be the only case where we want to suppress this action.

**Comment by CarlosNZ** [comment]
> However, I just checked the latest Angola snapshot (on 50008), and there is nothing actually set for the "defaultValue" in that field. Should there be?

Oh my bad, I was looking at the wrong one. All good on Angola. Please update the Fiji one too (and then export that as the new "master" version of that template)

**Comment by CarlosNZ** [comment]
This is done on Fiji now.
